// This file is automatically generated and contains assets from bsctestnet.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x64544969ed7EBf5f083679233325356EbE738930');
export const BUSD_ADDRESS = Address.fromString('0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee');
export const USDT_ADDRESS = Address.fromString('0x337610d27c682E347C9cD60BD4b3b107C9d34dDd');
export const DAI_ADDRESS = Address.fromString('0xEC5dCb5Dbf4B114C9d0F65BcCAb49EC54F6A0867');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x64544969ed7EBf5f083679233325356EbE738930'), // USDC
    Address.fromString('0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee'), // BUSD
    Address.fromString('0x337610d27c682E347C9cD60BD4b3b107C9d34dDd'), // USDT
    Address.fromString('0xEC5dCb5Dbf4B114C9d0F65BcCAb49EC54F6A0867'), // DAI
  ],
  pricingAssets: [
    Address.fromString('0xd66c6B4F0be8CE5b39D52E0Fd1344c389929B378'), // ETH
    Address.fromString('0xE906CBeCd4A17DF62B8d6c8C82F3882af25295f5'), // WBNB
    Address.fromString('0x6ce8dA28E2f864420840cF74474eFf5fD80E65B8'), // BTCB
    Address.fromString('0xa83575490D7df4E2F47b7D38ef351a2722cA45b9'), // XRP
    Address.fromString('0x8197E8f4C358B9be57a09c6063bA4591Ea502E98'), // ADA
    Address.fromString('0x14D440Cd12F99B676491cD6E7e606AD0F7ea9C51'), // AVAX
    Address.fromString('0x2397355a668Bb2b8B70A2873F1EB559b21ed1A8d'), // MATIC
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
